%YAML:1.0

#--------------------------------------------------------------------------------------------
# GPU Parameters
#--------------------------------------------------------------------------------------------

gpu.use_gpu: 1
gpu.is_jetson: 0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 718.856
Camera.fy: 718.856
Camera.cx: 607.1928
Camera.cy: 185.2157

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0

Camera.width: 1241
Camera.height: 376

# Camera frames per second 
Camera.fps: 10.0

# stereo baseline times fx
Camera.bf: 386.1448

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 35

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
ORBextractor.tile_h: 25
ORBextractor.tile_w: 25
ORBextractor.fixed_multi_scale_tile_size: 0
ORBextractor.apply_nms_ms: 1
ORBextractor.nms_ms_mode_gpu: 1

ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 1

# ORB Extractor: Fast threshold

# Firstly we impose th_FAST_MAX. If no corners are detected we impose a lower value th_FAST_MIN
# You can lower these values if your images have low contrast			

ORBextractor.th_FAST_MIN: 7
ORBextractor.th_FAST_MAX: 60

ORBextractor.FAST_N_MIN: 9
ORBextractor.FAST_N_MAX: 14


#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.6
Viewer.KeyFrameLineWidth: 2
Viewer.GraphLineWidth: 1
Viewer.PointSize:2
Viewer.CameraSize: 0.7
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -100
Viewer.ViewpointZ: -0.1
Viewer.ViewpointF: 500

